name: Pull request labeler
on:
  pull_request:
    branches: [ master ]
jobs:
  label:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
